package cz.osu.student.R19584.Problem_0XX.Problem_00X;

/*

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

 */

public class Problem_002 {
    public static int main() {
        int first = 0, second = 1, sum = 0, fibonacci_number;
        while(true) {
            fibonacci_number = first + second;
            if(fibonacci_number > 4000000) break;
            first = second;
            second = fibonacci_number;
            if(second % 2 == 0) sum += second;
        }
        return sum;
    }
}
