package cz.osu.student.R19584.Problem_0XX.Problem_04X;

import SharedCodeBase.HexagonalNumber;
import SharedCodeBase.PentagonalNumber;
import SharedCodeBase.TriangleNumber;

import java.util.HashSet;

/*

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

 */

public class Problem_045 {
    public static long main() {
        HashSet<Long> P = new HashSet<>();
        HashSet<Long> H = new HashSet<>();
        for(long add = 1; ; add++) {
            long check = TriangleNumber.get(285 + add);
            P.add(PentagonalNumber.get(165 + add));
            H.add(HexagonalNumber.get(143 + add));
            if (P.contains(check) && H.contains(check)) return check;
        }
    }
}
