package cz.osu.student.R19584.Problem_0XX.Problem_04X;

import SharedCodeBase.PentagonalNumber;

import java.util.ArrayList;

/*

Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

 */

public class Problem_044 {
    public static long main() {

        ArrayList<Long> pentagonalNumbers = new ArrayList<>();

        for(int n = 1000; n <= 3250; n++) pentagonalNumbers.add(PentagonalNumber.get(n));

        for(int j = 0; j < pentagonalNumbers.size() - 1; j++) {
            for (int k = j; k < pentagonalNumbers.size(); k++) {
                long a = pentagonalNumbers.get(j);
                long b = pentagonalNumbers.get(k);
                if (pentagonalNumbers.contains(a + b) && pentagonalNumbers.contains(b - a)) return Math.abs(b - a);
            }
        }
        return -1;
    }
}
