package cz.osu.student.R19584.Problem_0XX.Problem_01X;

/*

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

 */

public class Problem_012 {
    public static long main() {
        long sum = 0, divisor_count = 0;
        for(long number = 1; divisor_count < 500; number++) {
            divisor_count = 0;
            sum += number;
            for (long i = 2; i <= Math.sqrt(sum); i++) if (sum % i == 0) divisor_count += 2;
        }
        return sum;
    }
}
