package cz.osu.student.R19584.Problem_0XX.Problem_06X;

/*

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:

Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Square	 	    P4,n=n^2 	        1, 4, 9, 16, 25, ...
Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.

The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

 */


import SharedCodeBase.*;

public class Problem_061 {

    private static final long[] solution = new long[6];
    private static final long[][] numbers = new long[6][];

    public static long main() {

        int i;

        for(i = 0; i < 6; i++) numbers[i] = new long[141];

        for(i = 0; i < 122; i++) {
            numbers[0][i] = TriangleNumber.get(i + 19);
            numbers[1][i] = SquareNumber.get(i + 19);
            numbers[2][i] = PentagonalNumber.get(i + 19);
            numbers[3][i] = HexagonalNumber.get(i + 19);
            numbers[4][i] = HeptagonalNumber.get(i + 19);
            numbers[5][i] = OctagonalNumber.get(i + 19);
        }

        for (i = 0; i < numbers[5].length; i++) {
            solution[5] = numbers[5][2];
            FindNext(5, 1);
        }

        return solution[0] + solution[1] + solution[2] + solution[3] + solution[4] + solution[5];
    }

    public static boolean FindNext(int last, int length) {
        for (int i = 0; i < solution.length; i++) {
            if (solution[i] < 1000) {
                for (int j = 0; j < numbers[i].length; j++) {
                    boolean unique = true;
                    for (long l : solution) {
                        if (numbers[i][j] == l) {
                            unique = false;
                            break;
                        }
                    }
                    if (unique && ((numbers[i][j] / 100) == (solution[last] % 100))) {
                        solution[i] = numbers[i][j];
                        if (length == 5 && solution[5] / 100 == solution[i] % 100) return true;
                        if (FindNext(i, length + 1)) return true;
                    }
                }
                solution[i] = 0;
            }
        }
        return false;
    }
}
